Add github-specific stuff.
EternalCodeTeam/GitCheck pull request #11
Opened 2023-01-31 09:23 UTC by Jakubk15

Features like issue templates and renovate need to be added manually, as I don't have access for this repo's settings.

2023-02-07 22:30 UTC, Rollczi requested changes

2023-02-07 22:30 UTC, Rollczi commented on build.gradle.kts
> +    gradlePluginPortal()
Proszę to wywalić.

2023-02-18 07:32 UTC, Jakubk15 commented on build.gradle.kts
> +    gradlePluginPortal()
Dzięki, poprawione 😄

2023-02-19 14:43 UTC, vLuckyyy approved these changes

2023-02-21 16:37 UTC, merged